sudo: false
language: python
python:
  - "3.4"
  - "3.5"
env:
  - RELAY_DATABASE_TYPE=postgresql
  - RELAY_DATABASE_TYPE=mysql
services:
  - redis-server
  - postgresql
  - mysql
install:
  - pip install -U pip setuptools
  - pip install -U -r requirements/development.txt
  - sh -c "if [ '$RELAY_DATABASE_TYPE' = 'postgresql' ]; then pip install -U -r requirements/postgresql.txt; fi"
  - sh -c "if [ '$RELAY_DATABASE_TYPE' = 'mysql' ]; then pip install -U -r requirements/mysql.txt; fi"
  - pip freeze
cache:
  directories:
    - $HOME/.cache/pip
    - bower_components/
before_script:
  - npm install -g bower
  - bower install
  - sh -c "if [ '$RELAY_DATABASE_TYPE' = 'postgresql' ]; then psql -c 'create database socialrelaytest owner postgres;' -U postgres; fi"
  - sh -c "if [ '$RELAY_DATABASE_TYPE' = 'mysql' ]; then mysql -e 'CREATE DATABASE socialrelaytest;'; fi"
script: py.test --cov=./
after_success:
  - codecov
