---
# Code
- name: Get latest socialrelay code
  become_user: socialrelay
  git: accept_hostkey=yes dest=/home/socialrelay/socialrelay repo=https://github.com/jaywink/social-relay.git force=yes version={{ socialrelay_version }}
  notify:
    - restart worker
    - restart jobs
    - restart web

# Requirements
- name: Install app requirements
  become_user: socialrelay
  pip: requirements=/home/socialrelay/socialrelay/requirements/production.txt virtualenv=/home/socialrelay/venv
  notify:
    - restart worker
    - restart jobs
    - restart web
- name: Install PostgreSQL requirements
  become_user: socialrelay
  pip: requirements=/home/socialrelay/socialrelay/requirements/postgresql.txt virtualenv=/home/socialrelay/venv
  notify:
    - restart worker
    - restart jobs
    - restart web
  when: socialrelay_database == "postgresql"

# Settings
- name: Create local settings
  become_user: socialrelay
  template: dest=/home/socialrelay/socialrelay/social_relay/local_config.py src=local_config.py.j2
  notify:
    - restart worker
    - restart jobs
    - restart web

# Database
- name: Run migrations
  become_user: socialrelay
  script: venv_exec.sh arnold up 0
  notify:
    - restart worker
    - restart jobs
    - restart web

# Bower
- name: Install bower statics
  become_user: socialrelay
  bower: path=/home/socialrelay/socialrelay

# Upstart
- name: Set up worker upstart job
  template: dest=/etc/init/socialrelay-worker.conf src=socialrelay-worker.conf.j2
  notify:
    - restart worker
- name: Set up scheduled jobs upstart job
  template: dest=/etc/init/socialrelay-jobs.conf src=socialrelay-jobs.conf.j2
  notify:
    - restart jobs
- name: Set up web upstart job
  template: dest=/etc/init/socialrelay-web.conf src=socialrelay-web.conf.j2
  notify:
    - restart web
